// Generated by CoffeeScript 1.7.1
var compresser, compresser_opt, compresser_opts, fs, options, _i, _len;

compresser = require('./compresser.js');

fs = require('fs');

compresser_opts = fs.readFileSync('/home/jukin/code/weixing/hairdressing/.compresser', 'utf-8');

options = {};

compresser_opts = compresser_opts.split('\n');

for (_i = 0, _len = compresser_opts.length; _i < _len; _i++) {
  compresser_opt = compresser_opts[_i];
  compresser_opt = compresser_opt.split(':');
  options[compresser_opt[0]] = RegExp(compresser_opt[1].trim(), 'g');
}

options.rootPath = '/home/jukin/code/weixing/hairdressing';

console.log(options);

compresser.compress(options);
